include:
  - local: gitlab-deploy-template.yml
stages:
  - deploy

variables:
  CI_VAR: "the variable value from CI"
  USING_REPO_README: "true"
  # DRAWIO_EDITOR_URL: https://de.vicp.net:25053
  # KITY_MINDER_EDITOR_URL: https://de.vicp.net:25053
  DEPLOY_ENV:
    description: "Select the deployment environment"
    value: "staging"
    options:
      - "staging"
      - "deploy"
