theme: jekyll-theme-minimal
title: ShaoOrg's homepage
description: Bookmark this to keep an eye on my project updates!
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Conversion
markdown:    kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
