# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: GitHub Pages CI
on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: "Select deployment environment"
        required: true
        default: "staging"
        type: string
      COMBIND_REACT_WORKFLOW_NAME:
        description: "combind react build dist folder into mkdocs material"
        required: false
        default: ""
        type: string
      USING_REPO_README:
        description: "using repo readme.md to replace index.md"
        required: false
        default: ""
        type: string

jobs:
  # Build job
  build:
    runs-on: [ ubuntu-latest ]
    if: ${{ inputs.DEPLOY_ENV == 'deploy' }} || github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      DRAWIO_EDITOR_URL: https://de.vicp.net:25053
      KITY_MINDER_EDITOR_URL: https://de.vicp.net:25053
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-mkdocs-material
        with:
          DEPLOY_ENV: ${{inputs.DEPLOY_ENV}}
          COMBIND_REACT_WORKFLOW_NAME: ${{inputs.COMBIND_REACT_WORKFLOW_NAME}}
          USING_REPO_README: ${{inputs.USING_REPO_README}}
      - name: Deploy site to GHES Pages
        if: ${{ github.server_url != 'https://github.com' }}
        uses: ./.github/actions/deploy-gh-pages-in-ghes
      - name: Deploy site to Github Cloud Pages
        if: ${{ github.server_url == 'https://github.com' }}
        uses: ./.github/actions/deploy-gh-pages-in-github-com
